name: Deploy Conditional Access Policy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="client_id= c14f7b34-dfb2-4fad-b5d4-140f7e4c180e "\
            -var="client_secret= ra98Q~AdPpqEiDfszHsEBC5K54ybKHxC6Qkm6cy1" \
            -var="tenant_id= 4db1d822-dd16-4b4c-a18b-4eed8f5949f1 "

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="client_id= c14f7b34-dfb2-4fad-b5d4-140f7e4c180e " \
            -var="client_secret= ra98Q~AdPpqEiDfszHsEBC5K54ybKHxC6Qkm6cy1 " \
            -var="tenant_id= 4db1d822-dd16-4b4c-a18b-4eed8f5949f1"
